package com.example.backendproject.entities;

public enum BlockType {
    CHECKBOX,
    RADIO,
    INPUT_TEXT,
    INPUT_NUMBER,
    HIGHLIGHT_TEXT,
    TEXT,
    IMAGE,
    VIDEO,
    COLOR,
    CORRESPONDANCE_RIGHT,
    CORRESPONDANCE_LEFT,
    DRAG_DROP_IMAGE_LIST,
    ARROW_LEFT,
    BREAK,
    ARROW_RIGHT,
    COLORATE_TEXT,
    QUESTION, DEFAULT,AUDIO,AUDIO_IMAGE,
    IMAGE_WITH_TEXT,
    EQUATION,
    TABLE,
    ANSWER_TO_STROKE,
    TEXT_TO_SEPARATE,
    WORD_TO_STROKE,
    MATH_STRING,
    SHAPES_IMAGES_TO_COLOR
}
